/**
 * Sends a daily HTML report based on dynamic data in the Google Sheet.
 * Optimized for flexibility and easy client configuration (a professional selling point).
 */
function sendDailyReportOptimized() {
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  
  // 1. SETUP: Get sheets by name (using English naming conventions for configuration)
  var reportSheet = spreadsheet.getSheetByName("Report Data");
  var configSheet = spreadsheet.getSheetByName("Config"); // Configuration Sheet

  // Error Handling: Check if sheets exist
  if (!reportSheet || !configSheet) {
    Logger.log("Error: 'Report Data' or 'Config' sheet not found.");
    return;
  }

  // 2. DYNAMIC CONFIGURATION: Get settings from the 'Config' Sheet
  // This allows the client to change parameters without touching the script.
  var recipientEmail = configSheet.getRange("B1").getValue(); // Recipient Email (Cell B1)
  var emailSubject = configSheet.getRange("B2").getValue();   // Email Subject (Cell B2)

  if (recipientEmail === "") {
    Logger.log("Error: Recipient email is empty in Config sheet.");
    return;
  }

  // 3. DYNAMIC DATA RANGE: Get data up to the last row
  var lastRow = reportSheet.getLastRow();
  
  // Check if there is data (Row > 1 because Row 1 is header)
  if (lastRow < 2) {
    Logger.log("No data found to report.");
    return;
  }

  // getRange(startRow, startColumn, numRows, numColumns)
  // numRows = lastRow - 1 (subtracting the header row)
  var dataRange = reportSheet.getRange(2, 1, lastRow - 1, 3);
  var data = dataRange.getValues();

  // 4. HTML CONSTRUCTION (Creating a clean, professional-looking table)
  var htmlBody = "<h3>Daily Sales Report - Date " + new Date().toLocaleDateString('en-US') + "</h3>";
  htmlBody += "<table border='1' cellpadding='5' style='border-collapse:collapse; width:100%; font-family: Arial, sans-serif;'>";
  
  // Get headers dynamically from Row 1 of the Report Sheet
  var headers = reportSheet.getRange("A1:C1").getValues()[0];
  htmlBody += "<tr style='background-color:#007BFF; color: white;'>";
  headers.forEach(header => {
    htmlBody += "<th>" + header + "</th>";
  });
  htmlBody += "</tr>";

  // Loop through data and create table rows
  for (var i = 0; i < data.length; i++) {
    var row = data[i];
    
    // Create alternating row colors (Zebra striping) for readability
    var rowColor = (i % 2 === 0) ? "#f2ffdf" : "#ffffff";
    
    htmlBody += "<tr style='background-color:" + rowColor + ";'>";
    htmlBody += "<td>" + row[0] + "</td>"; // Column 1 data
    htmlBody += "<td>" + row[1] + "</td>"; // Column 2 data
    htmlBody += "<td>" + row[2] + "</td>"; // Column 3 data
    htmlBody += "</tr>";
  }
  htmlBody += "</table>";
  htmlBody += "<p><em>This email was automatically generated by Google Apps Script.</em></p>";

  // 5. SEND EMAIL
  MailApp.sendEmail({
    to: recipientEmail,
    subject: emailSubject || "Automated Report", 
    htmlBody: htmlBody
  });

  Logger.log("Email sent successfully to: " + recipientEmail);
}
